import type {
  Appointment,
  Claim,
  Clinician,
  Location,
} from "../types/models";

export const sampleLocations: Location[] = [
  {
    locationId: "loc-001",
    name: "HealthCore Austin Central",
    city: "Austin",
    stateOrCountry: "TX",
    country: "US",
    phone: "(512) 340-8800",
    averageConsultationFee: {
      primary_care: 120,
      chronic_disease: 160,
      preventive: 140,
      specialist: 220,
      womens_health: 180,
      paediatric: 130,
      mental_health: 170,
    },
  },
  {
    locationId: "loc-002",
    name: "HealthCore Miami",
    city: "Miami",
    stateOrCountry: "FL",
    country: "US",
    phone: "(305) 510-7700",
    averageConsultationFee: {
      primary_care: 130,
      chronic_disease: 170,
      preventive: 150,
      specialist: 240,
      womens_health: 190,
      paediatric: 140,
      mental_health: 180,
    },
  },
  {
    locationId: "loc-003",
    name: "HealthCore London",
    city: "London",
    stateOrCountry: "England",
    country: "UK",
    phone: "+44 20 7946 0958",
    averageConsultationFee: {
      primary_care: 110,
      chronic_disease: 150,
      preventive: 130,
      specialist: 210,
      womens_health: 170,
      paediatric: 120,
      mental_health: 160,
    },
  },
];

export const sampleClaims: Claim[] = [
  {
    claimId: "CLM-1001",
    patientId: "HC-AB1234",
    locationId: "loc-001",
    serviceType: "primary_care",
    payerName: "Aetna",
    payerId: "PAYER-01",
    submissionDate: "2026-09-01",
    claimAmount: 420.5,
    status: "submitted",
    resubmitted: false,
  },
  {
    claimId: "CLM-1002",
    patientId: "HC-CD2345",
    locationId: "loc-001",
    serviceType: "specialist",
    payerName: "BlueCross",
    payerId: "PAYER-02",
    submissionDate: "2026-08-21",
    claimAmount: 900,
    status: "denied",
    denialReason: "coding_error",
    resubmitted: false,
  },
  {
    claimId: "CLM-1003",
    patientId: "HC-EF3456",
    locationId: "loc-002",
    serviceType: "preventive",
    payerName: "Aetna",
    payerId: "PAYER-01",
    submissionDate: "2026-08-11",
    claimAmount: 260,
    status: "approved",
    resubmitted: false,
  },
  {
    claimId: "CLM-1004",
    patientId: "HC-GH4567",
    locationId: "loc-002",
    serviceType: "mental_health",
    payerName: "Cigna",
    payerId: "PAYER-03",
    submissionDate: "2026-08-12",
    claimAmount: 730,
    status: "denied",
    denialReason: "missing_authorisation",
    resubmitted: true,
  },
  {
    claimId: "CLM-1005",
    patientId: "HC-IJ5678",
    locationId: "loc-003",
    serviceType: "chronic_disease",
    payerName: "BlueCross",
    payerId: "PAYER-02",
    submissionDate: "2026-09-04",
    claimAmount: 615,
    status: "pending",
    resubmitted: false,
  },
  {
    claimId: "CLM-1006",
    patientId: "HC-KL6789",
    locationId: "loc-003",
    serviceType: "womens_health",
    payerName: "Cigna",
    payerId: "PAYER-03",
    submissionDate: "2026-09-05",
    claimAmount: 510,
    status: "approved",
    resubmitted: false,
  },
];

export const sampleAppointments: Appointment[] = [
  {
    appointmentId: "APT-1001",
    patientId: "HC-AB1234",
    locationId: "loc-001",
    serviceType: "primary_care",
    scheduledDate: "2026-09-09",
    scheduledTime: "09:00",
    status: "scheduled",
  },
  {
    appointmentId: "APT-1002",
    patientId: "HC-CD2345",
    locationId: "loc-001",
    serviceType: "specialist",
    scheduledDate: "2026-09-10",
    scheduledTime: "11:30",
    status: "no_show",
    noShowReason: "Late transportation",
  },
  {
    appointmentId: "APT-1003",
    patientId: "HC-EF3456",
    locationId: "loc-002",
    serviceType: "preventive",
    scheduledDate: "2026-09-08",
    scheduledTime: "14:00",
    status: "confirmed",
    confirmedAt: "2026-09-06T09:15:00",
  },
  {
    appointmentId: "APT-1004",
    patientId: "HC-GH4567",
    locationId: "loc-002",
    serviceType: "mental_health",
    scheduledDate: "2026-09-11",
    scheduledTime: "15:30",
    status: "no_show",
    noShowReason: "Patient missed appointment",
  },
  {
    appointmentId: "APT-1005",
    patientId: "HC-IJ5678",
    locationId: "loc-003",
    serviceType: "chronic_disease",
    scheduledDate: "2026-09-07",
    scheduledTime: "10:15",
    status: "completed",
  },
];

export const sampleClinicians: Clinician[] = [
  {
    clinicianId: "CLN-001",
    firstName: "Maria",
    lastName: "Lopez",
    role: "physician",
    locationId: "loc-001",
    licenceState: "TX",
    licenceExpiryDate: "2027-03-15",
    cmeHoursRequired: 30,
    cmeHoursLogged: 11,
    cmeYearStartDate: "2026-01-01",
  },
  {
    clinicianId: "CLN-002",
    firstName: "Daniel",
    lastName: "Ng",
    role: "nurse_practitioner",
    locationId: "loc-002",
    licenceState: "FL",
    licenceExpiryDate: "2026-09-20",
    cmeHoursRequired: 35,
    cmeHoursLogged: 32,
    cmeYearStartDate: "2026-01-01",
  },
  {
    clinicianId: "CLN-003",
    firstName: "Aisha",
    lastName: "Patel",
    role: "nurse",
    locationId: "loc-003",
    licenceState: "ENG",
    licenceExpiryDate: "2026-09-15",
    cmeHoursRequired: 25,
    cmeHoursLogged: 25,
    cmeYearStartDate: "2025-09-01",
  },
];
